name: Scraping
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Modules
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium
      - name: Running Script
        run: python pilates.py
      - name: Commit and Push Changes
        run: |
          git config user.name "Github Action"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pilates/*.json
          timestamp=$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
